#maven plugin help mojo generation informations
#Tue Dec 30 23:39:12 CST 2025
destinationDirectory=D\:\\Users\\XKY\\Documents\\AA\u5B66\u4E60\u5C0F\u7EC4PPT\u7B49\u6587\u4EF6\\Java\\kaoshitest\\target\\generated-sources\\plugin
helpPackageName=org.example
